### ISSUE TITLE
Build failures on python 3.15

### ISSUE THREAD

**Issue by sanjayankur31** [jim-easterbrook/python-exiv2#64]
python-exiv2 fails to build with Python 3.15.0a6.

```
  src/swig-0_28_7/xmp_wrap.cxx: In function ‘void _process_list(PyObject*, bool, Exiv2::XmpData::iterator*, Exiv2::XmpData::iterator*)’:
  src/swig-0_28_7/xmp_wrap.cxx:5790:18: error: ‘PyWeakref_GetObject’ was not declared in this scope; did you mean ‘PyWeakref_GetRef’?
   5790 |         py_ptr = PyWeakref_GetObject(PyList_GetItem(list, idx-1));
        |                  ^~~~~~~~~~~~~~~~~~~
        |                  PyWeakref_GetRef

```
https://docs.python.org/3.15/whatsnew/3.15.html

Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2440690

**Comment by jim-easterbrook** [comment]
SWIG (used to generate the python-exiv2 wrappers) does not yet fully support Python 3.15
https://github.com/swig/swig/blob/master/RELEASENOTES

However, this use of `PyWeakref_GetObject` is in my interface file so it needs to be replaced before Python 3.15 is released. Thanks for the bug report.

**Comment by jim-easterbrook** [comment]
Commit 8a666d2 should fix this. SWIG support for Python 3.15 is better than I thought. I'll do a new release of python-exiv2 after Python 3.15 is released.

**Comment by jim-easterbrook** [comment]
Release 0.19.0 has this fix, but does not include Python 3.15 binary wheels.

**Comment by jim-easterbrook** [comment]
Release 0.19.1 includes binary wheels for Python 3.15.
